version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lstm_prediction_api
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
      - ../ml/model:/app/ml/model
    environment:
      - LOG_LEVEL=INFO
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible
    deploy:  # Add GPU resource requirements
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Adjust based on your needs
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s